# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Default

steps:

- script: # script path or inline
  workingDirectory: cd C:\PruebaPipeline
  displayName: 'Cambiando de directorio'
  failOnStderr: 'Fallo cambiando de directorio'
  env: { string: string } # mapping of environment variables to add

- script:
    cd D:\PruebaDevOps
  displayName: 'Intentando crear pruebaDevops'

- script:
    npm-cli-login -u ci24 -p $controles$ -e jequesada@gmail.com
  displayName: 'logeando npm'

- script: 
    npm install ci
  displayName: 'Instalando modulos'  

- script:
    node backup.js
  displayName: 'Intentando correr backup.js'
