# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool: Default

steps:

- script: 
  workingDirectory: C:\PruebaPipeline
  displayName: 'Cambiando de directorio'
  failOnStderr: 'Fallo cambiando de directorio'

- script: npm-cli-login -u ci24 -p $controles$ -e jequesada@gmail.com
  workingDirectory: C:\PruebaPipeline
  displayName: 'logeando npm'

- script: npm install ci
  workingDirectory: C:\PruebaPipeline
  displayName: 'Instalando modulos'  

- script: node backup.js
  workingDirectory: C:\PruebaPipeline
  displayName: 'Intentando correr backup.js'
